ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_miller_ate.h File Reference
bls12_miller_ate.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/bls12_twist.h>
#include <ELiPS_bn_bls/bls12_p8sparse.h>
#include <ELiPS_bn_bls/bls12_line_ate.h>
Functions
void bls12_Miller_algo_for_plain_ate (Fp12 *ANS, EFp12 *Q, EFp12 *P)
Detailed Description
Interaface for BLS12 Miller's algo for unoptimized version of ate pairing.
Definition in file bls12_miller_ate.h.
Function Documentation
bls12_Miller_algo_for_plain_ate()
void bls12_Miller_algo_for_plain_ate (Fp12 * ANS, EFp12 * Q, EFp12 * P)
Calculate Miller's loop for ate pairing in BLS12 curve.
Parameters
[out] ANS - output in Fp12
[in] Q - Input rational point Q in G2.
[in] P - Input rational point P in G1.
Definition at line 31 of file bls12_miller_ate.c.
References bls12_EFp12_to_EFp(), bls12_EFp12_to_EFp2(), bls12_f_ltq(), bls12_ff_ltt(), bls12_Pseudo_8_sparse_mapping(), curve_parameters, EFp12_clear(), EFp12_init(), EFp2_clear(), EFp2_init(), EFp2_set(), EFp2_set_neg(), EFp_clear(), EFp_init(), Fp_clear(), Fp_init(), Fp_set_ui(), and curve_params::trace_t.
Referenced by bls12_plain_ate().
{
     EFp12 Buf;
     EFp12_init(&Buf);
     EFp2 T;
     EFp2_init(&T);
     EFp2 mapped_Q,mapped_Q_neg,mapped_Q1,mapped_Q2_neg;
     EFp2_init(&mapped_Q);
     EFp2_init(&mapped_Q_neg);
     EFp2_init(&mapped_Q1);
     EFp2_init(&mapped_Q2_neg);
     EFp mapped_P;
     EFp_init(&mapped_P);
     Fp12 f;
     Fp12_init(&f);
     Fp L;
     Fp_init(&L);
     int i,length;
     mpz_t loop;
     mpz_init(loop);
     //set
     bls12_EFp12_to_EFp(&mapped_P,P);  //set P
     bls12_EFp12_to_EFp2(&mapped_Q,Q);//set mapped_Q
     bls12_Pseudo_8_sparse_mapping(&mapped_P,&mapped_Q,&L);
     EFp2_set_neg(&mapped_Q_neg,&mapped_Q);//set mapped_Q_neg
     EFp2_set(&T,&mapped_Q_neg);    //set T
     Fp12_set_ui(&f,0);            //set f
     Fp_set_ui(&f.x0.x0.x0,1);
     mpz_sub_ui(loop,curve_parameters.trace_t,1);
     mpz_neg(loop,loop);
     length=(int)mpz_sizeinbase(loop,2);
     char binary[length];
     mpz_get_str(binary,2,loop);
     //miller
     for(i=1; i<length; i++){
         bls12_ff_ltt(&f,&T,&mapped_P,&L);
         if(binary[i]=='1'){
             bls12_f_ltq(&f,&T,&mapped_Q_neg,&mapped_P,&L);
         }
     }
     Fp12_set(ANS,&f);
     mpz_clear(loop);
     EFp12_clear(&Buf);
     Fp12_clear(&f);
     EFp2_clear(&T);
     EFp2_clear(&mapped_Q);
     EFp2_clear(&mapped_Q_neg);
     EFp2_clear(&mapped_Q1);
     EFp2_clear(&mapped_Q2_neg);
     EFp_clear(&mapped_P);
     Fp_clear(&L);
 }