ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_timeprint.h File Reference
bls12_timeprint.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <stdio.h>
Functions
void bls12_print_parameters (void)
void bls12_print_G1_point (void)
void bls12_print_G2_point (void)
void bls12_print_tate_time (void)
void bls12_print_plain_ate_time (void)
void bls12_print_opt_ate_time (void)
void bls12_print_final_exp_plain_time (void)
void bls12_print_final_exp_optimal_time (void)
void bls12_print_plain_G1_scm_time (void)
void bls12_print_2split_G1_scm_time (void)
void bls12_print_plain_G2_scm_time (void)
void bls12_print_2split_G2_scm_time (void)
void bls12_print_4split_G2_scm_time (void)
void bls12_print_plain_G3_exp_time (void)
void bls12_print_2split_G3_exp_time (void)
void bls12_print_4split_G3_exp_time (void)
Variables
double bls12_MILLER_TATE
Detailed Description
Interaface for BLS12's time profiling
Definition in file bls12_timeprint.h.
Function Documentation
bls12_print_2split_G1_scm_time()
void bls12_print_2split_G1_scm_time (void)
Prints 2 split of scalr G1 scm time: BLS12 curve
Definition at line 61 of file bls12_timeprint.c.
Referenced by bls12_test_G1_scm().
{
     printf("2split-G1-SCM time:%.2f[ms]\n",bls12_G1SCM_2SPLIT);
 }
bls12_print_2split_G2_scm_time()
void bls12_print_2split_G2_scm_time (void)
Prints 2 split of scalr G2 scm time: BLS12 curve
Definition at line 69 of file bls12_timeprint.c.
Referenced by bls12_test_G2_scm().
{
     printf("2split-G2-SCM time:%.2f[ms]\n",bls12_G2SCM_2SPLIT);
 }
bls12_print_2split_G3_exp_time()
void bls12_print_2split_G3_exp_time (void)
Prints 2 split of scalr G3 exponentiation time: BLS12 curve
Definition at line 81 of file bls12_timeprint.c.
Referenced by bls12_test_G3_exp().
{
     printf("2split-G3-SCM time:%.2f[ms]\n",bls12_G3EXP_2SPLIT);
 }
bls12_print_4split_G2_scm_time()
void bls12_print_4split_G2_scm_time (void)
Prints 4 split of scalr G2 scm time: BLS12 curve
Definition at line 73 of file bls12_timeprint.c.
Referenced by bls12_test_G2_scm().
{
     printf("4split-G2-SCM time:%.2f[ms]\n",bls12_G2SCM_4SPLIT);
 }
bls12_print_4split_G3_exp_time()
void bls12_print_4split_G3_exp_time (void)
Prints 2 split of scalr G3 exponentiation time: BLS12 curve
Definition at line 85 of file bls12_timeprint.c.
Referenced by bls12_test_G3_exp().
{
     printf("4split-G3-SCM time:%.2f[ms]\n",bls12_G3EXP_4SPLIT);
 }
bls12_print_final_exp_optimal_time()
void bls12_print_final_exp_optimal_time (void)
Prints efficient final exp time: BLS12 curve
Definition at line 53 of file bls12_timeprint.c.
Referenced by bls12_test_opt_ate_pairing(), bls12_test_plain_ate_pairing(), and bls12_test_tate_pairing().
{
     printf("optimal-final exp time:%.2f[ms]\n",bls12_FINALEXP_OPT);
 }
bls12_print_final_exp_plain_time()
void bls12_print_final_exp_plain_time (void)
Prints plain final exp time: BLS12 curve
Definition at line 49 of file bls12_timeprint.c.
{
     printf("plain-final exp time:%.2f[ms]\n",bls12_FINALEXP_PLAIN);
 }
bls12_print_G1_point()
void bls12_print_G1_point (void)
Prints G1 rational point: BLS12 curve
bls12_print_G2_point()
void bls12_print_G2_point (void)
Prints G2 rational point: BLS12 curve
bls12_print_opt_ate_time()
void bls12_print_opt_ate_time (void)
Prints opt-ate paring time: BLS12 curve
Definition at line 45 of file bls12_timeprint.c.
Referenced by bls12_test_opt_ate_pairing().
{
     printf("miller opt-ate time:%.2f[ms]\n",bls12_MILLER_OPTATE);
 }
bls12_print_parameters()
void bls12_print_parameters (void)
Prints curve parameter: BLS12 curve
Definition at line 478 of file curve_settings.c.
{
     printf("====================================================================================\n");
     printf("bls12\n\n");
     gmp_printf("parameters\n");
     gmp_printf("X     (%dbit length) : %Zd \n",(int)mpz_sizeinbase(bls12_X,2),bls12_X);
     gmp_printf("prime (%dbit length) : %Zd \n",(int)mpz_sizeinbase(curve_parameters.prime,2),curve_parameters.prime);
     gmp_printf("order (%dbit length) : %Zd \n",(int)mpz_sizeinbase(curve_parameters.order,2),curve_parameters.order);
     gmp_printf("trace (%dbit length) : %Zd \n",(int)mpz_sizeinbase(curve_parameters.trace_t,2),curve_parameters.trace_t);
     gmp_printf("\nelliptic curve\n");
     gmp_printf("E:y^2=x^3+4\n",curve_parameters.curve_b);
     gmp_printf("\nmodulo polynomial\n");
     gmp_printf("Fp2  : f(x) = x^2+1\n");
     gmp_printf("Fp6  : f(x) = x^3-(alpha+1)\n");
     gmp_printf("Fp12 : f(x) = x^2-beta\n");
 }
bls12_print_plain_ate_time()
void bls12_print_plain_ate_time (void)
Prints ate paring time: BLS12 curve
Definition at line 41 of file bls12_timeprint.c.
Referenced by bls12_test_plain_ate_pairing().
{
     printf("miller plain-ate time:%.2f[ms]\n",bls12_MILLER_PLAINATE);
 }
bls12_print_plain_G1_scm_time()
void bls12_print_plain_G1_scm_time (void)
Prints plain G1 scm time: BLS12 curve
Definition at line 57 of file bls12_timeprint.c.
Referenced by bls12_test_G1_scm().
{
     printf("plain-G1-SCM time:%.2f[ms]\n",bls12_G1SCM_PLAIN);
 }
bls12_print_plain_G2_scm_time()
void bls12_print_plain_G2_scm_time (void)
Prints plain G2 scm time: BLS12 curve
Definition at line 65 of file bls12_timeprint.c.
Referenced by bls12_test_G2_scm().
{
     printf("plain-G2-SCM time:%.2f[ms]\n",bls12_G2SCM_PLAIN);
 }
bls12_print_plain_G3_exp_time()
void bls12_print_plain_G3_exp_time (void)
Prints no split of scalr G3 exponentiation time: BLS12 curve
Definition at line 77 of file bls12_timeprint.c.
Referenced by bls12_test_G3_exp().
{
     printf("plain-G3-SCM time:%.2f[ms]\n",bls12_G3EXP_PLAIN);
 }
bls12_print_tate_time()
void bls12_print_tate_time (void)
Prints Tate paring time: BLS12 curve
Definition at line 37 of file bls12_timeprint.c.
References bls12_MILLER_TATE.
Referenced by bls12_test_tate_pairing().
{
     printf("miller tate time:%.2f[ms]\n",bls12_MILLER_TATE);
 }
Variable Documentation
bls12_MILLER_TATE
double bls12_MILLER_TATE
Time types of different operations.
Definition at line 31 of file bls12_timeprint.c.
Referenced by bls12_print_tate_time(), and bls12_tate().