ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_pairings.h File Reference
bls12_pairings.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/bls12_miller_ate.h>
#include <ELiPS_bn_bls/bls12_miller_tate.h>
#include <ELiPS_bn_bls/bls12_miller_optate.h>
#include <ELiPS_bn_bls/bls12_finalexp.h>
#include <ELiPS_bn_bls/bls12_timeprint.h>
#include <ELiPS_bn_bls/bn_utils.h>
Functions
void bls12_tate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
void bls12_plain_ate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
void bls12_opt_ate (Fp12 *ANS, EFp12 *P, EFp12 *Q)
Detailed Description
Interaface for BLS12 Pairing implementations
Definition in file bls12_pairings.h.
Function Documentation
bls12_opt_ate()
void bls12_opt_ate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
Calculate optimal ate pairing in BLS12 curve.
Parameters
[out] ANS - output
[in] P - P in G1 mapped to Fp12.
[in] Q - Q in G2.
Definition at line 59 of file bls12_pairings.c.
References bls12_Miller_algo_for_opt_ate().
Referenced by bls12_test_G3_exp(), and bls12_test_opt_ate_pairing().
{
     //miller
     gettimeofday(&t0,NULL);
     bls12_Miller_algo_for_opt_ate(ANS,P,Q);
     gettimeofday(&t1,NULL);
     bls12_MILLER_OPTATE=timedifference_msec(t0,t1);
     //final exp
     gettimeofday(&t0,NULL);
     bls12_finalexp_optimal(ANS,ANS);
     gettimeofday(&t1,NULL);
     bls12_FINALEXP_OPT=timedifference_msec(t0,t1);
 }
bls12_plain_ate()
void bls12_plain_ate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
Calculate ate pairing in BLS12 curve.
Parameters
[out] ANS - output
[in] P - P in G1 mapped to Fp12.
[in] Q - Q in G2.
Definition at line 45 of file bls12_pairings.c.
References bls12_Miller_algo_for_plain_ate().
Referenced by bls12_test_plain_ate_pairing().
{
     //miller
     gettimeofday(&t0,NULL);
     bls12_Miller_algo_for_plain_ate(ANS,P,Q);
     gettimeofday(&t1,NULL);
     bls12_MILLER_PLAINATE=timedifference_msec(t0,t1);
     //final exp
     gettimeofday(&t0,NULL);
     bls12_finalexp_optimal(ANS,ANS);
     gettimeofday(&t1,NULL);
     bls12_FINALEXP_OPT=timedifference_msec(t0,t1);
 }
bls12_tate()
void bls12_tate (Fp12 * ANS, EFp12 * P, EFp12 * Q)
Calculate tate pairing in BLS12 curve.
Parameters
[out] ANS - output
[in] P - P in G1 mapped to Fp12.
[in] Q - Q in G2.
Definition at line 31 of file bls12_pairings.c.
References bls12_finalexp_optimal(), bls12_Miller_algo_for_tate(), and bls12_MILLER_TATE.
Referenced by bls12_test_tate_pairing().
{
     //miller
     gettimeofday(&t0,NULL);
     bls12_Miller_algo_for_tate(ANS,P,Q);
     gettimeofday(&t1,NULL);
     bls12_MILLER_TATE=timedifference_msec(t0,t1);
     //final exp
     gettimeofday(&t0,NULL);
     bls12_finalexp_optimal(ANS,ANS);
     gettimeofday(&t1,NULL);
     bls12_FINALEXP_OPT=timedifference_msec(t0,t1);
 }