ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_twist.h File Reference
bls12_twist.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/bn_efp12.h>
Functions
void bls12_EFp12_to_EFp2 (EFp2 *ANS, EFp12 *P)
void bls12_EFp2_to_EFp12 (EFp12 *ANS, EFp2 *P)
void bls12_EFp12_to_EFp (EFp *ANS, EFp12 *P)
void bls12_EFp_to_EFp12 (EFp12 *ANS, EFp *P)
Detailed Description
Interaface for BLS12's rational point mapping functionalities
Definition in file bls12_twist.h.
Function Documentation
bls12_EFp12_to_EFp()
void bls12_EFp12_to_EFp (EFp * ANS, EFp12 * P)
Calculate primary twist of G1 rational point
Parameters
[out] ANS - output in EFp
[in] P - input P in EFp12.
Definition at line 32 of file bls12_twist.c.
References Fp_set(), EFp::infinity, and EFp::y.
Referenced by bls12_2split_G1_scm(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_Miller_algo_for_tate(), and bls12_plain_G1_scm().
{
     Fp_set(&ANS->x,&P->x.x0.x0.x0);
     Fp_set(&ANS->y,&P->y.x0.x0.x0);
     ANS->infinity=P->infinity;
 }
bls12_EFp12_to_EFp2()
void bls12_EFp12_to_EFp2 (EFp2 * ANS, EFp12 * P)
Calculate sextic twisted map G2 rational point
Parameters
[out] ANS - output in EFp2
[in] P - input P in EFp12.
Definition at line 45 of file bls12_twist.c.
References Fp2_set(), and Fp2_set_ui().
Referenced by bls12_2split_G2_scm(), bls12_4split_G2_scm(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), and bls12_plain_G2_scm().
{
     Fp2_set_ui(&ANS->x,0);
     Fp2_set(&ANS->x,&P->x.x0.x2);
     Fp2_mul_basis(&ANS->x,&ANS->x);
     Fp2_set_ui(&ANS->y,0);
     Fp2_set(&ANS->y,&P->y.x1.x1);
     Fp2_mul_basis(&ANS->y,&ANS->y);
     ANS->infinity=P->infinity;
 }
bls12_EFp2_to_EFp12()
void bls12_EFp2_to_EFp12 (EFp12 * ANS, EFp2 * P)
Calculate sextic twisted map G2 rational point
Parameters
[out] ANS - output in EFp12
[in] P - input P in EFp2.
Definition at line 55 of file bls12_twist.c.
References Fp2_set().
Referenced by bls12_plain_G2_scm().
{
     Fp12_set_ui(&ANS->x,0);
     Fp2_set(&ANS->x.x0.x2,&P->x);
     Fp2_inv_basis(&ANS->x.x0.x2,&ANS->x.x0.x2);
     Fp12_set_ui(&ANS->y,0);
     Fp2_set(&ANS->y.x1.x1,&P->y);
     Fp2_inv_basis(&ANS->y.x1.x1,&ANS->y.x1.x1);
     ANS->infinity=P->infinity;
 }
bls12_EFp_to_EFp12()
void bls12_EFp_to_EFp12 (EFp12 * ANS, EFp * P)
Calculate primary twist of G1 rational point
Parameters
[out] ANS - output in EFp12
[in] P - input P in EFp.
Definition at line 38 of file bls12_twist.c.
References Fp_set(), EFp::infinity, and EFp::y.
Referenced by bls12_generate_G1_point(), and bls12_plain_G1_scm().
{
     Fp_set(&ANS->x.x0.x0.x0,&P->x);
     Fp_set(&ANS->y.x0.x0.x0,&P->y);
     ANS->infinity=P->infinity;
 }