ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_line_tate.h File Reference
bls12_line_tate.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/bn_efp12.h>
Functions
void bls12_ff_ltt_vtt_for_tate (Fp12 *f, EFp *T, EFp12 *Q)
void bls12_f_ltp_vtp_for_tate (Fp12 *f, EFp *T, EFp *P, EFp12 *Q)
Detailed Description
Interaface for BLS12 line evaluation for tate pairing.
Definition in file bls12_line_tate.h.
Function Documentation
bls12_f_ltp_vtp_for_tate()
void bls12_f_ltp_vtp_for_tate (Fp12 * f, EFp * T, EFp * P, EFp12 * Q)
Calculate line equation for tate pairing in BLS12 curve.
Parameters
[out] f - output in Fp12
[in] T - Input rational point T in Fp.
[in] P - Input rational point P in Fp.
[in] Q - Input rational point Q mapped in Fp22.
Definition at line 151 of file bls12_line_tate.c.
References EFp_clear(), EFp_init(), EFp_set(), Fp_clear(), Fp_init(), Fp_sub(), EFp::infinity, and EFp::y.
Referenced by bls12_Miller_algo_for_tate().
{
     EFp Next_T;
     EFp_init(&Next_T);
     Fp12 tmp1,tmp2,tmp3;
     Fp12_init(&tmp1);
     Fp12_init(&tmp2);
     Fp12_init(&tmp3);
     Fp lambda;
     Fp_init(&lambda);
     bls12_EFp_ECA_return_lambda(&Next_T,&lambda,T,P);
     switch(Next_T.infinity){
         case 0:
             Fp12_set(&tmp3,&Q->x);
             Fp_sub(&tmp3.x0.x0.x0,&Q->x.x0.x0.x0,&P->x);
             Fp12_mul_mpz(&tmp3,&tmp3,lambda.x0);
             Fp12_set(&tmp1,&Q->y);
             Fp_sub(&tmp1.x0.x0.x0,&Q->y.x0.x0.x0,&P->y);
             Fp12_sub(&tmp1,&tmp1,&tmp3);
             Fp12_set(&tmp2,&Q->x);
             Fp_sub(&tmp2.x0.x0.x0,&Q->x.x0.x0.x0,&Next_T.x);
             Fp12_inv(&tmp3,&tmp2);
             Fp12_mul(&tmp2,f,&tmp1);
             Fp12_mul(f,&tmp2,&tmp3);
             break;
         case 1:
             Fp12_set(&tmp1,&Q->x);
             Fp_sub(&tmp1.x0.x0.x0,&Q->x.x0.x0.x0,&T->x);
             Fp12_mul(f,f,&tmp1);
             break;
         default:
             break;
     }
     EFp_set(T,&Next_T);
     EFp_clear(&Next_T);
     Fp12_clear(&tmp1);
     Fp12_clear(&tmp2);
     Fp12_clear(&tmp3);
     Fp_clear(&lambda);
 }
bls12_ff_ltt_vtt_for_tate()
void bls12_ff_ltt_vtt_for_tate (Fp12 * f, EFp * T, EFp12 * Q)
Calculate line equation for tate pairing in BLS12 curve.
Parameters
[out] f - output in Fp12
[in] T - Input rational point T in Fp.
[in] Q - Input rational point Q mapped in Fp22.
Definition at line 106 of file bls12_line_tate.c.
References EFp_clear(), EFp_init(), EFp_set(), Fp_clear(), Fp_init(), Fp_sub(), EFp::infinity, and EFp::y.
Referenced by bls12_Miller_algo_for_tate().
{
     EFp Next_T;
     EFp_init(&Next_T);
     Fp12 tmp1,tmp2,tmp3;
     Fp12_init(&tmp1);
     Fp12_init(&tmp2);
     Fp12_init(&tmp3);
     Fp lambda;
     Fp_init(&lambda);
     bls12_EFp_ECD_return_lambda(&Next_T,&lambda,T);
     switch(Next_T.infinity){
         case 0:
             Fp12_sqr(&tmp1,f);
             Fp12_set(&tmp3,&Q->x);
             Fp_sub(&tmp3.x0.x0.x0,&Q->x.x0.x0.x0,&T->x);
             Fp12_mul_mpz(&tmp3,&tmp3,lambda.x0);
             Fp12_set(&tmp2,&Q->y);
             Fp_sub(&tmp2.x0.x0.x0,&Q->y.x0.x0.x0,&T->y);
             Fp12_sub(&tmp2,&tmp2,&tmp3);
             Fp12_set(&tmp3,&Q->x);
             Fp_sub(&tmp3.x0.x0.x0,&Q->x.x0.x0.x0,&Next_T.x);
             Fp12_inv(&tmp3,&tmp3);
             Fp12_mul(&tmp1,&tmp1,&tmp2);
             Fp12_mul(f,&tmp1,&tmp3);
             break;
         case 1:
             Fp12_sqr(&tmp1,f);
             Fp12_set(&tmp2,&Q->x);
             Fp_sub(&tmp2.x0.x0.x0,&Q->x.x0.x0.x0,&T->x);
             Fp12_mul(f,&tmp1,&tmp2);
             break;
         default:
             break;
     }
     EFp_set(T,&Next_T);
     EFp_clear(&Next_T);
     Fp12_clear(&tmp1);
     Fp12_clear(&tmp2);
     Fp12_clear(&tmp3);
     Fp_clear(&lambda);
 }