ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_miller_tate.h File Reference
bls12_miller_tate.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/bls12_line_tate.h>
#include <ELiPS_bn_bls/bls12_twist.h>
Functions
void bls12_Miller_algo_for_tate (Fp12 *ANS, EFp12 *Q, EFp12 *P)
Detailed Description
Interaface for BLS12 Miller's algo of tate pairing.
Definition in file bls12_miller_tate.h.
Function Documentation
bls12_Miller_algo_for_tate()
void bls12_Miller_algo_for_tate (Fp12 * ANS, EFp12 * Q, EFp12 * P)
Calculate Miller's loop for tate pairing in BLS12 curve.
Parameters
[out] ANS - output in Fp12
[in] Q - Input rational point Q in G2.
[in] P - Input rational point P in G1.
Definition at line 32 of file bls12_miller_tate.c.
References bls12_EFp12_to_EFp(), bls12_f_ltp_vtp_for_tate(), bls12_ff_ltt_vtt_for_tate(), curve_parameters, EFp_clear(), EFp_init(), EFp_set(), Fp_set_ui(), and curve_params::order.
Referenced by bls12_tate().
{
     EFp Tmp_P,T;
     EFp_init(&Tmp_P);
     EFp_init(&T);
     Fp12 f;
     Fp12_init(&f);
     int i,length;
     length=(int)mpz_sizeinbase(curve_parameters.order,2);
     char binary[length];
     mpz_get_str(binary,2,curve_parameters.order);
     //set
     bls12_EFp12_to_EFp(&Tmp_P,P);
     EFp_set(&T,&Tmp_P);
     Fp12_set_ui(&f,0);
     Fp_set_ui(&f.x0.x0.x0,1);
     //miller
     for(i=1; i<length; i++){
         bls12_ff_ltt_vtt_for_tate(&f,&T,Q);
         if(binary[i]=='1'){
             bls12_f_ltp_vtp_for_tate(&f,&T,&Tmp_P,Q);
         }
     }
     Fp12_set(ANS,&f);
     Fp12_clear(&f);
     EFp_clear(&T);
     EFp_clear(&Tmp_P);
 }