ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_generate_points.h File Reference
bls12_generate_points.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/curve_settings.h>
#include <ELiPS_bn_bls/bls12_twist.h>
#include <ELiPS_bn_bls/bls12_frobenius.h>
Functions
void bls12_generate_G1_point (EFp12 *P)
void bls12_generate_G2_point (EFp12 *Q)
void bls12_generate_random_point (EFp12 *R)
Detailed Description
Header of generating rational point for BLS12 over Fp12 extension field.
Definition in file bls12_generate_points.h.
Function Documentation
bls12_generate_G1_point()
void bls12_generate_G1_point (EFp12 * P)
Generates rational point P in G1 group. Usally generated in prime field but maps it to Fp12 for using in pairing. where G1*G2->G3 is the bilinear pairing.
Parameters
[out] P - the generated point.
[in] P - the input vecotr initialized as 'EFp12 P' point by 'EFp12_init' function.
Definition at line 33 of file bls12_generate_points.c.
References bls12_EFp_to_EFp12(), curve_parameters, EFp12_SCM(), EFp_clear(), EFp_init(), EFp_rational_point_bls12(), curve_params::EFp_total, EFp::infinity, and curve_params::order.
Referenced by bls12_test_G1_scm(), bls12_test_G3_exp(), bls12_test_opt_ate_pairing(), bls12_test_plain_ate_pairing(), and bls12_test_tate_pairing().
{
     EFp Tmp_P;
     EFp_init(&Tmp_P);
     mpz_t scalar;
     mpz_init(scalar);
     EFp_rational_point_bls12(&Tmp_P);
     bls12_EFp_to_EFp12(P,&Tmp_P);
     mpz_tdiv_q(scalar,curve_parameters.EFp_total,curve_parameters.order);
     EFp12_SCM(P,P,scalar);
     P->infinity=Tmp_P.infinity;
     EFp_clear(&Tmp_P);
     mpz_clear(scalar);
 }
bls12_generate_G2_point()
void bls12_generate_G2_point (EFp12 * Q)
Generates special rational point Q in G2 group. where G1*G2->G3 is the bilinear pairing.
Parameters
[out] Q - the generated point.
[in] Q - the input vecotr initialized as 'EFp12 Q' point by 'EFp12_init' function.
Definition at line 49 of file bls12_generate_points.c.
References bls12_Fp12_frobenius_map_p1(), curve_parameters, EFp12_clear(), EFp12_ECA(), EFp12_init(), EFp12_rational_point_bls12(), EFp12_SCM(), EFp12_set_neg(), curve_params::EFpd_total, and curve_params::order.
Referenced by bls12_test_G2_scm(), bls12_test_G3_exp(), bls12_test_opt_ate_pairing(), and bls12_test_plain_ate_pairing().
{
     EFp12 random_P,P,frobenius_P;
     EFp12_init(&random_P);
     EFp12_init(&P);
     EFp12_init(&frobenius_P);
     mpz_t exp;
     mpz_init(exp);
     EFp12_rational_point_bls12(&random_P);
     mpz_pow_ui(exp,curve_parameters.order,2);
     mpz_tdiv_q(exp,curve_parameters.EFpd_total,exp);
     EFp12_SCM(&P,&random_P,exp);
     bls12_Fp12_frobenius_map_p1(&frobenius_P.x,&P.x);
     bls12_Fp12_frobenius_map_p1(&frobenius_P.y,&P.y);
     frobenius_P.infinity=P.infinity;
     EFp12_set_neg(&P,&P);
     EFp12_ECA(Q,&P,&frobenius_P);
     mpz_clear(exp);
     EFp12_clear(&random_P);
     EFp12_clear(&P);
     EFp12_clear(&frobenius_P);
 }
bls12_generate_random_point()
void bls12_generate_random_point (EFp12 * R)
Generates random rational point R in the BLS12 curve over Fp12.
Parameters
[out] R - the generated point.
[in] R - the input vecotr initialized as 'EFp12 P' point by 'EFp12_init'.
Definition at line 73 of file bls12_generate_points.c.
References EFp12_init(), and EFp12_rational_point_bls12().
{
     EFp12_init(R);
     EFp12_rational_point_bls12(R);
 }