ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_miller_optate.h File Reference
bls12_miller_optate.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/bls12_twist.h>
#include <ELiPS_bn_bls/bls12_p8sparse.h>
#include <ELiPS_bn_bls/bls12_line_ate.h>
Functions
void bls12_Miller_algo_for_opt_ate (Fp12 *ANS, EFp12 *Q, EFp12 *P)
Detailed Description
Interaface for BLS12 Miller's algo of optimal-ate pairing.
Definition in file bls12_miller_optate.h.
Function Documentation
bls12_Miller_algo_for_opt_ate()
void bls12_Miller_algo_for_opt_ate (Fp12 * ANS, EFp12 * Q, EFp12 * P)
Calculate Miller's loop for optimal ate pairing in BLS12 curve.
Parameters
[out] ANS - output in Fp12
[in] Q - Input rational point Q in G2.
[in] P - Input rational point P in G1.
Definition at line 31 of file bls12_miller_optate.c.
References bls12_EFp12_to_EFp(), bls12_EFp12_to_EFp2(), bls12_f_ltq(), bls12_ff_ltt(), bls12_Pseudo_8_sparse_mapping(), bls12_X_binary, bls12_X_length, EFp2_clear(), EFp2_init(), EFp2_set(), EFp2_set_neg(), EFp_clear(), EFp_init(), Fp_clear(), Fp_init(), and Fp_set_ui().
Referenced by bls12_opt_ate().
{
     EFp2 T;
     EFp2_init(&T);
     EFp2 mapped_Q,mapped_Q_neg,mapped_Q1,mapped_Q2_neg;
     EFp2_init(&mapped_Q);
     EFp2_init(&mapped_Q_neg);
     EFp2_init(&mapped_Q1);
     EFp2_init(&mapped_Q2_neg);
     EFp mapped_P;
     EFp_init(&mapped_P);
     Fp12 f;
     Fp12_init(&f);
     Fp L;
     Fp_init(&L);
     int i;
     //set
     bls12_EFp12_to_EFp(&mapped_P,P);  //set P
     bls12_EFp12_to_EFp2(&mapped_Q,Q);//set mapped_Q
     bls12_Pseudo_8_sparse_mapping(&mapped_P,&mapped_Q,&L);
     EFp2_set_neg(&mapped_Q_neg,&mapped_Q);//set mapped_Q_neg
     EFp2_set(&T,&mapped_Q_neg);        //set T
     Fp12_set_ui(&f,0);            //set f
     Fp_set_ui(&f.x0.x0.x0,1);
     //miller
     for(i=bls12_X_length-1; i>=0; i--){
         switch(bls12_X_binary[i]){
             case 0:
                 bls12_ff_ltt(&f,&T,&mapped_P,&L);
                 break;
             case 1:
                 bls12_ff_ltt(&f,&T,&mapped_P,&L);
                 bls12_f_ltq(&f,&T,&mapped_Q,&mapped_P,&L);
                 break;
             case -1:
                 bls12_ff_ltt(&f,&T,&mapped_P,&L);
                 bls12_f_ltq(&f,&T,&mapped_Q_neg,&mapped_P,&L);
                 break;
             default:
                 break;
         }
     }
     Fp12_set(ANS,&f);
     Fp12_clear(&f);
     EFp2_clear(&T);
     EFp2_clear(&mapped_Q);
     EFp2_clear(&mapped_Q_neg);
     EFp2_clear(&mapped_Q1);
     EFp2_clear(&mapped_Q2_neg);
     EFp_clear(&mapped_P);
     Fp_clear(&L);
 }