ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bls12_skew_frobenius.h File Reference
bls12_skew_frobenius.h File Reference
Paring over BARRETO-LYNN-SCOTT curve of embedding degree 12 related files.
#include <ELiPS_bn_bls/bn_bls12_precoms.h>
#include <ELiPS_bn_bls/bn_efp12.h>
Functions
void bls12_EFp_skew_frobenius_map_p2 (EFp *ANS, EFp *A)
void bls12_EFp2_skew_frobenius_map_p1 (EFp2 *ANS, EFp2 *A)
void bls12_EFp2_skew_frobenius_map_p2 (EFp2 *ANS, EFp2 *A)
void bls12_EFp2_skew_frobenius_map_p3 (EFp2 *ANS, EFp2 *A)
void bls12_EFp2_skew_frobenius_map_p10 (EFp2 *ANS, EFp2 *A)
Detailed Description
Interaface for BLS12's Skew Frobenius map implementations
Definition in file bls12_skew_frobenius.h.
Function Documentation
bls12_EFp2_skew_frobenius_map_p1()
void bls12_EFp2_skew_frobenius_map_p1 (EFp2 * ANS, EFp2 * A)
Calculate Skew Frobenius map for pwer of p in G2 of BLS12 curve
Parameters
[out] ANS - output in G2'
[in] A - A in EFp2.
Definition at line 36 of file bls12_skew_frobenius.c.
References d12_skew_frobenius_constant, Fp2_mul(), Fp_set(), and Fp_set_neg().
Referenced by bls12_4split_G2_scm().
{
     //x
     Fp_set(&ANS->x.x0,&A->x.x0);
     Fp_set_neg(&ANS->x.x1,&A->x.x1);
     Fp2_mul(&ANS->x,&ANS->x,&d12_skew_frobenius_constant[f_p1][0]);
     //y
     Fp_set(&ANS->y.x0,&A->y.x0);
     Fp_set_neg(&ANS->y.x1,&A->y.x1);
     Fp2_mul(&ANS->y,&ANS->y,&d12_skew_frobenius_constant[f_p1][1]);
 }
bls12_EFp2_skew_frobenius_map_p10()
void bls12_EFp2_skew_frobenius_map_p10 (EFp2 * ANS, EFp2 * A)
Calculate Skew Frobenius map for pwer of p^10 in G2 of BLS12 curve
Parameters
[out] ANS - output in G2'
[in] A - A in EFp2.
Definition at line 65 of file bls12_skew_frobenius.c.
References d12_skew_frobenius_constant, and Fp2_mul().
{
     //x
     Fp2_mul(&ANS->x,&A->x,&d12_skew_frobenius_constant[f_p10][0]);
     //y
     Fp2_mul(&ANS->y,&A->y,&d12_skew_frobenius_constant[f_p10][1]);
 }
bls12_EFp2_skew_frobenius_map_p2()
void bls12_EFp2_skew_frobenius_map_p2 (EFp2 * ANS, EFp2 * A)
Calculate Skew Frobenius map for pwer of p^2 in G2 of BLS12 curve
Parameters
[out] ANS - output in G2'
[in] A - A in EFp2.
Definition at line 47 of file bls12_skew_frobenius.c.
References d12_skew_frobenius_constant, and Fp2_mul().
Referenced by bls12_2split_G2_scm(), and bls12_4split_G2_scm().
{
     //x
     Fp2_mul(&ANS->x,&A->x,&d12_skew_frobenius_constant[f_p2][0]);
     //y
     Fp2_mul(&ANS->y,&A->y,&d12_skew_frobenius_constant[f_p2][1]);
 }
bls12_EFp2_skew_frobenius_map_p3()
void bls12_EFp2_skew_frobenius_map_p3 (EFp2 * ANS, EFp2 * A)
Calculate Skew Frobenius map for pwer of p^3 in G2 of BLS12 curve
Parameters
[out] ANS - output in G2'
[in] A - A in EFp2.
Definition at line 54 of file bls12_skew_frobenius.c.
References d12_skew_frobenius_constant, Fp2_mul(), Fp_set(), and Fp_set_neg().
Referenced by bls12_4split_G2_scm().
{
     //x
     Fp_set(&ANS->x.x0,&A->x.x0);
     Fp_set_neg(&ANS->x.x1,&A->x.x1);
     Fp2_mul(&ANS->x,&ANS->x,&d12_skew_frobenius_constant[f_p3][0]);
     //y
     Fp_set(&ANS->y.x0,&A->y.x0);
     Fp_set_neg(&ANS->y.x1,&A->y.x1);
     Fp2_mul(&ANS->y,&ANS->y,&d12_skew_frobenius_constant[f_p3][1]);
 }
bls12_EFp_skew_frobenius_map_p2()
void bls12_EFp_skew_frobenius_map_p2 (EFp * ANS, EFp * A)
Calculate Skew Frobenius map for p^2 in G1 of BLS12 curve
Parameters
[out] ANS - output in G1
[in] A - A in EFp.
Definition at line 31 of file bls12_skew_frobenius.c.
References epsilon1, Fp_mul_mpz(), Fp_set_neg(), and EFp::y.
Referenced by bls12_2split_G1_scm().
{
     Fp_mul_mpz(&ANS->x,&A->x,epsilon1);
     Fp_set_neg(&ANS->y,&A->y);
 }