ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bn_fp2.h File Reference
bn_fp2.h File Reference
Finite field construction
#include <ELiPS_bn_bls/bn_fp.h>
#include <ELiPS_bn_bls/field_dtype.h>
#include <ELiPS_bn_bls/bn_bls12_precoms.h>
Functions
void Fp2_init (Fp2 *A)
void Fp2_clear (Fp2 *A)
void Fp2_printf (Fp2 *A, char *str)
void Fp2_set (Fp2 *ANS, Fp2 *A)
void Fp2_set_ui (Fp2 *ANS, unsigned long int A)
void Fp2_set_mpz (Fp2 *ANS, mpz_t A)
void Fp2_set_neg (Fp2 *ANS, Fp2 *A)
void Fp2_set_random (Fp2 *ANS, gmp_randstate_t state)
void Fp2_mul (Fp2 *ANS, Fp2 *A, Fp2 *B)
Detailed Description
Interaface of degree 2 extension field (Fp2) operations
Definition in file bn_fp2.h.
Function Documentation
Fp2_clear()
void Fp2_clear (Fp2 * A)
Clears an Fp2 type struct from memory
Parameters
[in] A - input A is a pointer of Fp2 type struct.
Definition at line 38 of file bn_fp2.c.
References Fp_clear().
Referenced by clear_parameters(), and EFp2_clear().
                       {
     Fp_clear(&A->x0);
     Fp_clear(&A->x1);
 }
Fp2_init()
void Fp2_init (Fp2 * A)
Initializes an Fp2 type struct
Parameters
[in] A - input A is a pointer of Fp2 type struct.
Definition at line 33 of file bn_fp2.c.
References Fp_init().
Referenced by bls12_f_ltq(), bls12_ff_ltt(), bls12_Pseudo_8_sparse_mul(), EFp2_init(), EFp2_rational_point(), init_precoms(), and set_frobenius_constant().
                      {
     Fp_init(&A->x0);
     Fp_init(&A->x1);
 }
Fp2_mul()
void Fp2_mul (Fp2 * ANS, Fp2 * A, Fp2 * B)
Fp2 extension field multiplication with modular reduction for. Modular polynomial reduction x^2-c whre c has no sqare root in prime field Fp, needs to be defined before to use Fp_mul_basis function.
Parameters
[out] ANS - output ANS as pinter in Fp2.
[in] ANS - send ANS as pinter in Fp2. It will be returned as result of multiplication.
[in] A - send pointer A in Fp2.
[in] B - send pointer B in Fp2.
Definition at line 76 of file bn_fp2.c.
References Fp_add(), Fp_clear(), Fp_init(), Fp_mul(), Fp_mul_basis(), and Fp_sub().
Referenced by bls12_EFp2_skew_frobenius_map_p1(), bls12_EFp2_skew_frobenius_map_p10(), bls12_EFp2_skew_frobenius_map_p2(), bls12_EFp2_skew_frobenius_map_p3(), bls12_Fp12_frobenius_map_p3(), and bls12_Pseudo_8_sparse_mul().
{
     Fp tmp1,tmp2,tmp3,tmp4;
     Fp_init(&tmp1);
     Fp_init(&tmp2);
     Fp_init(&tmp3);
     Fp_init(&tmp4);
     //set
     Fp_mul(&tmp1,&A->x0,&B->x0);//a*c
     Fp_mul(&tmp2,&A->x1,&B->x1);//b*d
     Fp_add(&tmp3,&A->x0,&A->x1);//a+b
     Fp_add(&tmp4,&B->x0,&B->x1);//c+d
     //x0
     Fp_mul_basis(&ANS->x0,&tmp2);//b*d*v
     Fp_add(&ANS->x0,&ANS->x0,&tmp1);//a*c+b*d*v
     //x1
     Fp_mul(&ANS->x1,&tmp3,&tmp4);//(a+b)(c+d)
     Fp_sub(&ANS->x1,&ANS->x1,&tmp1);
     Fp_sub(&ANS->x1,&ANS->x1,&tmp2);
     //clear
     Fp_clear(&tmp1);
     Fp_clear(&tmp2);
     Fp_clear(&tmp3);
     Fp_clear(&tmp4);
 }
Fp2_printf()
void Fp2_printf (Fp2 * A, char * str)
Prints an Fp2 type struct
Parameters
[in] A - input A is a pointer of Fp2 type struct.
[in] str - input str is a string pointer.
Definition at line 43 of file bn_fp2.c.
References Fp_printf().
Referenced by EFp2_printf().
{
     gmp_printf("%s(",str);
     Fp_printf(&A->x0,"");
     gmp_printf(",");
     Fp_printf(&A->x1,"");
     gmp_printf(")");
 }
Fp2_set()
void Fp2_set (Fp2 * ANS, Fp2 * A)
Sets an Fp2 type struct to another Fp2 struct
Parameters
[out] ANS - input A is a pointer of Fp2 type struct.
[in] A - input A is a pointer of Fp2 type struct.
Definition at line 51 of file bn_fp2.c.
References Fp_set().
Referenced by bls12_EFp12_to_EFp2(), bls12_EFp2_to_EFp12(), bls12_Fp12_frobenius_map_p10(), bls12_Fp12_frobenius_map_p2(), bls12_Fp12_frobenius_map_p4(), bls12_Fp12_frobenius_map_p8(), EFp2_set(), and EFp2_set_neg().
{
     Fp_set(&ANS->x0,&A->x0);
     Fp_set(&ANS->x1,&A->x1);
 }
Fp2_set_mpz()
void Fp2_set_mpz (Fp2 * ANS, mpz_t A)
Sets an mpz_t type integer to another Fp2 struct. It calls the similar functions in Fp for each elements in Fp.
Parameters
[out] ANS - input A is a pointer of Fp2 type struct.
[in] A - input str is a string pointer.
Definition at line 61 of file bn_fp2.c.
References Fp_set_mpz().
Referenced by EFp2_set_mpz().
{
     Fp_set_mpz(&ANS->x0,A);
     Fp_set_mpz(&ANS->x1,A);
 }
Fp2_set_neg()
void Fp2_set_neg (Fp2 * ANS, Fp2 * A)
Negate A and sets it in ANS as a Fp2 vector. It calls Fp_set_neg fuctions for each elements.
Parameters
[out] ANS - set
[in] A - send A as Fp.
Definition at line 66 of file bn_fp2.c.
References Fp_set_neg().
Referenced by EFp2_set_neg().
{
     Fp_set_neg(&ANS->x0,&A->x0);
     Fp_set_neg(&ANS->x1,&A->x1);
 }
Fp2_set_random()
void Fp2_set_random (Fp2 * ANS, gmp_randstate_t state)
Sets a random Fp2 element in ANS where each Fp coefficient < prime
Parameters
[out] ANS - output an random Fp2 vector.
[in] state - send a gmp_randstate_t.
Definition at line 71 of file bn_fp2.c.
References Fp_set_random().
Referenced by EFp2_rational_point().
{
     Fp_set_random(&ANS->x0,state);
     Fp_set_random(&ANS->x1,state);
 }
Fp2_set_ui()
void Fp2_set_ui (Fp2 * ANS, unsigned long int A)
Sets an unsigned long int type element to another Fp2 struct
Parameters
[out] ANS - input A is a pointer of Fp2 type struct.
[in] A - input A is a unsigned long integer.
Definition at line 56 of file bn_fp2.c.
References Fp_set_ui().
Referenced by bls12_EFp12_to_EFp2(), EFp2_set_ui(), and set_basis().
{
     Fp_set_ui(&ANS->x0,UI);
     Fp_set_ui(&ANS->x1,UI);
 }