ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bn_fp.h File Reference
bn_fp.h File Reference
Finite field construction
#include <ELiPS_bn_bls/curve_settings.h>
#include <ELiPS_bn_bls/field_dtype.h>
Functions
void Fp_init (Fp *A)
void Fp_clear (Fp *A)
void Fp_printf (Fp *A, char *str)
void Fp_set (Fp *ANS, Fp *A)
void Fp_set_ui (Fp *ANS, unsigned long int A)
void Fp_set_mpz (Fp *ANS, mpz_t B)
void Fp_set_neg (Fp *ANS, Fp *A)
void Fp_set_random (Fp *ANS, gmp_randstate_t state)
void Fp_mul (Fp *ANS, Fp *A, Fp *B)
void Fp_mul_ui (Fp *ANS, Fp *A, unsigned long int B)
void Fp_mul_mpz (Fp *ANS, Fp *A, mpz_t B)
void Fp_mul_basis (Fp *ANS, Fp *A)
void Fp_mul_basis_KSS16 (Fp *ANS, Fp *A)
void Fp_add (Fp *ANS, Fp *A, Fp *B)
void Fp_add_ui (Fp *ANS, Fp *A, unsigned long int B)
void Fp_add_mpz (Fp *ANS, Fp *A, mpz_t B)
void Fp_sub (Fp *ANS, Fp *A, Fp *B)
void Fp_sub_ui (Fp *ANS, Fp *A, unsigned long int B)
void Fp_sub_mpz (Fp *ANS, Fp *A, mpz_t B)
void Fp_inv (Fp *ANS, Fp *A)
int Fp_legendre (Fp *A)
int Fp_isCNR (Fp *A)
void Fp_sqrt (Fp *ANS, Fp *A)
void Fp_pow (Fp *ANS, Fp *A, mpz_t scalar)
int Fp_cmp (Fp *A, Fp *B)
int Fp_cmp_ui (Fp *A, unsigned long int UI)
int Fp_cmp_mpz (Fp *A, mpz_t B)
int Fp_cmp_zero (Fp *A)
int Fp_cmp_one (Fp *A)
void Fp_neg (struct Fp *ANS, struct Fp *A)
Detailed Description
Interaface of prime field operations. Primarily targeted for BN and BLS12 curve
Definition in file bn_fp.h.
Function Documentation
Fp_add()
void Fp_add (Fp * ANS, Fp * A, Fp * B)
Prime field addition with reduction as ANS= A+B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send pointer B in Fp.
Definition at line 69 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by Fp2_mul().
{
     mpz_add(ANS->x0,A->x0,B->x0);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_add_mpz()
void Fp_add_mpz (Fp * ANS, Fp * A, mpz_t B)
Prime field addition with reduction as ANS= A+B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send mpz_t int B.
Definition at line 79 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by EFp_rational_point_bls12().
{
     mpz_add(ANS->x0,A->x0,B);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_add_ui()
void Fp_add_ui (Fp * ANS, Fp * A, unsigned long int B)
Prime field addition with reduction as ANS= A+B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send unsigned int B.
Definition at line 74 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
{
     mpz_add_ui(ANS->x0,A->x0,UI);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_clear()
void Fp_clear (Fp * A)
Clears memory an Fp type struct
Parameters
[in] A - input A is a pointer of Fp type struct.
Definition at line 17 of file bn_fp.c.
Referenced by bls12_f_ltp_vtp_for_tate(), bls12_ff_ltt_vtt_for_tate(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), clear_parameters(), EFp_clear(), EFp_ECA(), EFp_ECD(), EFp_rational_point_bls12(), EFp_rational_point_bn(), Fp2_clear(), Fp2_mul(), Fp_isCNR(), Fp_pow(), and Fp_sqrt().
                     {
     mpz_clear(A->x0);
 }
Fp_cmp()
int Fp_cmp (Fp * A, Fp * B)
Compares A and B in Fp
Parameters
[out] int - return 0 if A==B and 1 otherwise.
[in] A - send pointer A in Fp.
[in] B - send pointer B in Fp.
Definition at line 224 of file bn_fp.c.
Referenced by EFp_ECA().
{
     if(mpz_cmp(A->x0,B->x0)==0){
         return 0;
     }
     return 1;
 }
Fp_cmp_mpz()
int Fp_cmp_mpz (Fp * A, mpz_t B)
Compares A and B in Fp
Parameters
[out] int - return 0 if A==B and 1 otherwise.
[in] A - send pointer A in Fp.
[in] B - send pointer B in mpz_t.
Definition at line 238 of file bn_fp.c.
{
     if(mpz_cmp(A->x0,B)==0){
         return 0;
     }
     return 1;
 }
Fp_cmp_one()
int Fp_cmp_one (Fp * A)
Compares A == 1 in Fp
Parameters
[out] int - return 0 if A==1 and 1 otherwise.
[in] A - send pointer A in Fp.
Definition at line 252 of file bn_fp.c.
Referenced by Fp_isCNR().
                       {
     if(mpz_cmp_ui(A->x0,1)==0){
         return 0;
     }
     return 1;
 }
Fp_cmp_ui()
int Fp_cmp_ui (Fp * A, unsigned long int UI)
Compares A and B in Fp
Parameters
[out] int - return 0 if A==B and 1 otherwise.
[in] A - send pointer A in Fp.
[in] B - send pointer B in int.
Definition at line 231 of file bn_fp.c.
{
     if(mpz_cmp_ui(A->x0,UI)==0){
         return 0;
     }
     return 1;
 }
Fp_cmp_zero()
int Fp_cmp_zero (Fp * A)
Compares A == 0 in Fp
Parameters
[out] int - return 0 if A==0 and 1 otherwise.
[in] A - send pointer A in Fp.
[in] B - send pointer B in int.
Definition at line 245 of file bn_fp.c.
Referenced by EFp_ECD().
{
     if(mpz_cmp_ui(A->x0,0)==0){
         return 0;
     }
     return 1;
 }
Fp_init()
void Fp_init (Fp * A)
Initializes an Fp type struct
Parameters
[in] A - input A is a pointer of Fp type struct.
Definition at line 13 of file bn_fp.c.
Referenced by bls12_f_ltp_vtp_for_tate(), bls12_ff_ltt_vtt_for_tate(), bls12_Fp12_frobenius_map_p1(), bls12_Fp12_frobenius_map_p3(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_Pseudo_8_sparse_mapping(), EFp_ECA(), EFp_ECD(), EFp_init(), EFp_rational_point_bls12(), EFp_rational_point_bn(), Fp2_init(), Fp2_mul(), Fp_isCNR(), Fp_pow(), Fp_sqrt(), get_epsilon(), and init_precoms().
                    {
     mpz_init(A->x0);
 }
Fp_inv()
void Fp_inv (Fp * ANS, Fp * A)
Prime field inversion A^-1 mod prime
Parameters
[out] ANS - output A^-1 mod prime in Fp.
[in] A - send pointer A in Fp.
Definition at line 99 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by bls12_Pseudo_8_sparse_mapping(), EFp_ECA(), EFp_ECD(), and get_epsilon().
{
     mpz_invert(ANS->x0,A->x0,curve_parameters.prime);
 }
Fp_isCNR()
int Fp_isCNR (Fp * A)
Check if A has qubic root or not in prime field.
Parameters
[out] int - return 1 if A has CR and -1 CNR.
[in] A - send pointer A in Fp.
Definition at line 112 of file bn_fp.c.
References curve_parameters, Fp_clear(), Fp_cmp_one(), Fp_init(), Fp_pow(), and curve_params::prime.
                     {
     Fp tmp;
     Fp_init(&tmp);
     mpz_t exp;
     mpz_init(exp);
     mpz_sub_ui(exp,curve_parameters.prime,1);
     mpz_tdiv_q_ui(exp,exp,3);
     Fp_pow(&tmp,A,exp);
     if(Fp_cmp_one(&tmp)==0){
         mpz_clear(exp);
         Fp_clear(&tmp);
         return 1;
     }else{
         mpz_clear(exp);
         Fp_clear(&tmp);
         return -1;
     }
 }
Fp_legendre()
int Fp_legendre (Fp * A)
Calculate legendre symbol (A/prime) to determine A has any sqare root in prime field.
Parameters
[out] int - return 1 if A has QR and -1 for QNR.
[in] A - send pointer A in Fp.
Definition at line 108 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by EFp_rational_point_bls12(), EFp_rational_point_bn(), and Fp_sqrt().
{
     return mpz_legendre(A->x0,curve_parameters.prime);
 }
Fp_mul()
void Fp_mul (Fp * ANS, Fp * A, Fp * B)
Prime field multiplication with reduction as ANS= A*B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send pointer B in Fp.
Definition at line 45 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by bls12_Pseudo_8_sparse_mapping(), EFp_ECA(), EFp_ECD(), EFp_rational_point_bls12(), EFp_rational_point_bn(), Fp2_mul(), Fp_pow(), Fp_sqrt(), and get_epsilon().
{
     mpz_mul(ANS->x0,A->x0,B->x0);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_mul_basis()
void Fp_mul_basis (Fp * ANS, Fp * A)
Prime field multiplication with reduction as ANS= A*B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send basis element ^2 = some int
Definition at line 60 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by Fp2_mul().
{
     mpz_sub(ANS->x0,curve_parameters.prime,A->x0);
 }
Fp_mul_basis_KSS16()
void Fp_mul_basis_KSS16 (Fp * ANS, Fp * A)
Prime field multiplication with reduction as ANS= A*B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send basis element ^2 = c is a int
Definition at line 64 of file bn_fp.c.
References curve_params::curve_a, and curve_parameters.
{
     mpz_mul_ui(ANS->x0,A->x0,c1);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.curve_a);
 }
Fp_mul_mpz()
void Fp_mul_mpz (Fp * ANS, Fp * A, mpz_t B)
Prime field multiplication with reduction as ANS= A*B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send mpz_t .
Definition at line 55 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by bls12_EFp_skew_frobenius_map_p2().
{
     mpz_mul(ANS->x0,A->x0,B);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_mul_ui()
void Fp_mul_ui (Fp * ANS, Fp * A, unsigned long int B)
Prime field multiplication with reduction as ANS= A*B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send unsigned int.
Definition at line 50 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by EFp_ECD().
{
     mpz_mul_ui(ANS->x0,A->x0,UI);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_neg()
void Fp_neg (struct Fp * ANS, struct Fp * A)
Calculate -A in Fp
Parameters
[out] ANS - return -A.
[in] A - send pointer A in Fp.
Definition at line 259 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
{
     mpz_sub(ANS->x0,curve_parameters.prime,A->x0);
 }
Fp_pow()
void Fp_pow (Fp * ANS, Fp * A, mpz_t scalar)
Calculate A^mpz_t mod prime in prime field.
Parameters
[out] ANS - return 1 if A has CR and -1 CNR.
[in] A - send pointer A in Fp.
Definition at line 203 of file bn_fp.c.
References Fp_clear(), Fp_init(), Fp_mul(), and Fp_set().
Referenced by Fp_isCNR(), and Fp_sqrt().
{
     int i,length;
     length=(int)mpz_sizeinbase(scalar,2);
     char binary[length];
     mpz_get_str(binary,2,scalar);
     Fp tmp;
     Fp_init(&tmp);
     Fp_set(&tmp,A);
     for(i=1; i<length; i++){
         Fp_mul(&tmp,&tmp,&tmp);
         if(binary[i]=='1'){
             Fp_mul(&tmp,A,&tmp);
         }
     }
     Fp_set(ANS,&tmp);
     Fp_clear(&tmp);
 }
Fp_printf()
void Fp_printf (Fp * A, char * str)
Prints an Fp type struct
Parameters
[out] A - input A is a pointer of Fp type struct.
[in] str - any string pointer.
Definition at line 21 of file bn_fp.c.
Referenced by EFp_printf(), and Fp2_printf().
{
     gmp_printf("%s%Zd",str,A->x0);
 }
Fp_set()
void Fp_set (Fp * ANS, Fp * A)
Set an Fp type struct to ANS
Parameters
[out] ANS - set A in ANS.
[in] A - send A as pointer.
Definition at line 25 of file bn_fp.c.
Referenced by bls12_EFp12_to_EFp(), bls12_EFp2_skew_frobenius_map_p1(), bls12_EFp2_skew_frobenius_map_p3(), bls12_EFp_to_EFp12(), bls12_Fp12_frobenius_map_p1(), bls12_Fp12_frobenius_map_p3(), EFp_set(), EFp_set_neg(), Fp2_set(), Fp_pow(), and Fp_sqrt().
{
     mpz_set(ANS->x0,A->x0);
 }
Fp_set_mpz()
void Fp_set_mpz (Fp * ANS, mpz_t B)
Set an gmp int mpz in ANS Fp type struct.
Parameters
[out] ANS - set A in ANS.
[in] A - send A as mpz_t.
Definition at line 33 of file bn_fp.c.
Referenced by EFp_set_mpz(), and Fp2_set_mpz().
{
     mpz_set(ANS->x0,A);
 }
Fp_set_neg()
void Fp_set_neg (Fp * ANS, Fp * A)
Negate A and set it in ANS
Parameters
[out] ANS - set prime-A in ANS.
[in] A - send A as Fp.
Definition at line 37 of file bn_fp.c.
Referenced by bls12_EFp2_skew_frobenius_map_p1(), bls12_EFp2_skew_frobenius_map_p3(), bls12_EFp_skew_frobenius_map_p2(), bls12_Fp12_frobenius_map_p1(), bls12_Fp12_frobenius_map_p3(), EFp_set_neg(), and Fp2_set_neg().
{
     mpz_neg(ANS->x0,A->x0);
 }
Fp_set_random()
void Fp_set_random (Fp * ANS, gmp_randstate_t state)
Set random Fp of size <prime in ANS
Parameters
[out] ANS - output an Fp < prime.
[in] A - send a gmp_randstate_t.
Definition at line 41 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by EFp_rational_point_bls12(), EFp_rational_point_bn(), Fp2_set_random(), and Fp_sqrt().
{
     mpz_urandomm(ANS->x0,state,curve_parameters.prime);
 }
Fp_set_ui()
void Fp_set_ui (Fp * ANS, unsigned long int A)
Set an unsigned int in ANS Fp type struct.
Parameters
[out] ANS - set A in ANS.
[in] A - send A as UI.
Definition at line 29 of file bn_fp.c.
Referenced by bls12_2split_G3_exp(), bls12_4split_G3_exp(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_Miller_algo_for_tate(), EFp_set_ui(), Fp2_set_ui(), get_epsilon(), and set_basis().
{
     mpz_set_ui(ANS->x0,UI);
 }
Fp_sqrt()
void Fp_sqrt (Fp * ANS, Fp * A)
Calculate sqrt(A) mod prime using Toneli-Shanks alogrithm in prime field.
Parameters
[out] ANS - return 1 if A has CR and -1 CNR.
[in] A - send pointer A in Fp.
Definition at line 133 of file bn_fp.c.
References curve_parameters, Fp_clear(), Fp_init(), Fp_legendre(), Fp_mul(), Fp_pow(), Fp_set(), Fp_set_random(), and curve_params::prime.
Referenced by EFp_rational_point_bls12(), EFp_rational_point_bn(), and get_epsilon().
{
     Fp x,y,t,k,n,tmp;
     Fp_init(&x);
     Fp_init(&y);
     Fp_init(&t);
     Fp_init(&k);
     Fp_init(&n);
     Fp_init(&tmp);
     unsigned long int e,m;
     mpz_t exp,q,z,result;
     mpz_init(exp);
     mpz_init(q);
     mpz_init(z);
     mpz_init(result);
     gmp_randstate_t state;
     gmp_randinit_default (state);
     gmp_randseed_ui(state,(unsigned long)time(NULL));
     Fp_set_random(&n,state);
     while(Fp_legendre(&n)!=-1){
         Fp_set_random(&n,state);
     }
     mpz_sub_ui(q,curve_parameters.prime,1);
     mpz_mod_ui(result,q,2);
     e=0;
     while(mpz_cmp_ui(result,0)==0){
         mpz_tdiv_q_ui(q,q,2);
         mpz_mod_ui(result,q,2);
         e++;
     }
     Fp_pow(&y,&n,q);
     mpz_set_ui(z,e);
     mpz_sub_ui(exp,q,1);
     mpz_tdiv_q_ui(exp,exp,2);
     Fp_pow(&x,A,exp);
     Fp_mul(&tmp,&x,&x);
     Fp_mul(&k,&tmp,A);
     Fp_mul(&x,&x,A);
     while(mpz_cmp_ui(k.x0,1)!=0){
         m=1;
         mpz_ui_pow_ui(exp,2,m);
         Fp_pow(&tmp,&k,exp);
         while(mpz_cmp_ui(tmp.x0,1)!=0){
             m++;
             mpz_ui_pow_ui(exp,2,m);
             Fp_pow(&tmp,&k,exp);
         }
         mpz_sub_ui(exp,z,m);
         mpz_sub_ui(exp,exp,1);
         mpz_ui_pow_ui(result,2,mpz_get_ui(exp));
         Fp_pow(&t,&y,result);
         Fp_mul(&y,&t,&t);
         mpz_set_ui(z,m);
         Fp_mul(&x,&x,&t);
         Fp_mul(&k,&k,&y);
     }
     Fp_set(ANS,&x);
     mpz_clear(exp);
     mpz_clear(q);
     mpz_clear(z);
     mpz_clear(result);
     Fp_clear(&x);
     Fp_clear(&y);
     Fp_clear(&t);
     Fp_clear(&k);
     Fp_clear(&n);
     Fp_clear(&tmp);
 }
Fp_sub()
void Fp_sub (Fp * ANS, Fp * A, Fp * B)
Prime field subtraction with reduction as ANS= A-B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send pointer B.
Definition at line 84 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by bls12_f_ltp_vtp_for_tate(), bls12_ff_ltt_vtt_for_tate(), EFp_ECA(), EFp_ECD(), and Fp2_mul().
{
     mpz_sub(ANS->x0,A->x0,B->x0);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_sub_mpz()
void Fp_sub_mpz (Fp * ANS, Fp * A, mpz_t B)
Prime field subtraction with reduction as ANS = A-B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send mpz_t int B.
Definition at line 94 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by EFp_rational_point_bn().
{
     mpz_sub(ANS->x0,A->x0,B);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }
Fp_sub_ui()
void Fp_sub_ui (Fp * ANS, Fp * A, unsigned long int B)
Prime field subtraction with reduction as ANS= A-B mod prime
Parameters
[out] ANS - output ANS < prime in Fp.
[in] A - send pointer A in Fp.
[in] B - send int B.
Definition at line 89 of file bn_fp.c.
References curve_parameters, and curve_params::prime.
Referenced by get_epsilon().
{
     mpz_sub_ui(ANS->x0,A->x0,UI);
     mpz_mod(ANS->x0,ANS->x0,curve_parameters.prime);
 }