ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bn_efp2.h File Reference
bn_efp2.h File Reference
Paring over BARRETO-NAEHRIG (BN) Curve related files
#include <ELiPS_bn_bls/bn_efp.h>
Functions
void EFp2_init (EFp2 *P)
void EFp2_clear (EFp2 *P)
void EFp2_printf (EFp2 *P, char *str)
void EFp2_set (EFp2 *ANS, EFp2 *P)
void EFp2_set_ui (EFp2 *ANS, unsigned long int u)
void EFp2_set_mpz (EFp2 *ANS, mpz_t A)
void EFp2_set_neg (EFp2 *ANS, EFp2 *P)
void EFp2_rational_point (EFp2 *P)
void EFp2_ECD (EFp2 *ANS, EFp2 *P)
void EFp2_ECA (EFp2 *ANS, EFp2 *P1, EFp2 *P2)
void EFp2_SCM (EFp2 *ANS, EFp2 *P, mpz_t scalar)
Detailed Description
Interaface for elliptic cuve operation in BN and BLS12 curve in Fp2 extension field
Definition in file bn_efp2.h.
Function Documentation
EFp2_clear()
void EFp2_clear (EFp2 * P)
Clears an EFp2 type structure
Parameters
[in] P - input P in EFp2.
Definition at line 38 of file bn_efp2.c.
References Fp2_clear().
Referenced by bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_plain_G2_scm(), and EFp2_SCM().
{
     Fp2_clear(&P->x);
     Fp2_clear(&P->y);
 }
EFp2_ECA()
void EFp2_ECA (EFp2 * ANS, EFp2 * P1, EFp2 * P2)
ECA in EFp2 rational point
Parameters
[in] ANS - output.
[in] P1 - input P1 in EFp2.
[in] P2 - input P2 in EFp2.
Definition at line 138 of file bn_efp2.c.
References EFp2_set().
Referenced by bls12_2split_G2_scm(), bls12_4split_G2_scm(), and EFp2_SCM().
{
     if(P1->infinity==1){
         EFp2_set(ANS,P2);
         return;
     }else if(P2->infinity==1){
         EFp2_set(ANS,P1);
         return;
     }else if(Fp2_cmp(&P1->x,&P2->x)==0){
         if(Fp2_cmp(&P1->y,&P2->y)!=0){
             ANS->infinity=1;
             return;
         }else{
             EFp2_ECD(ANS,P1);
             return;
         }
     }
     EFp2 Tmp_P1,Tmp_P2;
     EFp2_init(&Tmp_P1);
     EFp2_set(&Tmp_P1,P1);
     EFp2_init(&Tmp_P2);
     EFp2_set(&Tmp_P2,P2);
     Fp2 tmp1,tmp2,lambda;
     Fp2_init(&tmp1);
     Fp2_init(&tmp2);
     Fp2_init(&lambda);
     Fp2_sub(&tmp1,&Tmp_P2.x,&Tmp_P1.x);
     Fp2_inv(&tmp1,&tmp1);
     Fp2_sub(&tmp2,&Tmp_P2.y,&Tmp_P1.y);
     Fp2_mul(&lambda,&tmp1,&tmp2);
     Fp2_sqr(&tmp1,&lambda);
     Fp2_sub(&tmp2,&tmp1,&Tmp_P1.x);
     Fp2_sub(&ANS->x,&tmp2,&Tmp_P2.x);
     Fp2_sub(&tmp1,&Tmp_P1.x,&ANS->x);
     Fp2_mul(&tmp2,&lambda,&tmp1);
     Fp2_sub(&ANS->y,&tmp2,&Tmp_P1.y);
     //clear
     Fp2_clear(&tmp1);
     Fp2_clear(&tmp2);
     Fp2_clear(&lambda);
     EFp2_clear(&Tmp_P1);
     EFp2_clear(&Tmp_P2);
 }
EFp2_ECD()
void EFp2_ECD (EFp2 * ANS, EFp2 * P)
ECD in EFp2 rational point
Parameters
[in] ANS - output.
[in] P - input P in EFp2.
Definition at line 103 of file bn_efp2.c.
Referenced by EFp2_SCM().
{
     if(Fp2_cmp_zero(&P->y)==0){
         ANS->infinity=1;
         return;
     }
     EFp2 Tmp_P;
     EFp2_init(&Tmp_P);
     EFp2_set(&Tmp_P,P);
     Fp2 tmp1,tmp2,lambda;
     Fp2_init(&tmp1);
     Fp2_init(&tmp2);
     Fp2_init(&lambda);
     Fp2_mul_ui(&tmp1,&Tmp_P.y,2);
     Fp2_inv(&tmp1,&tmp1);
     Fp2_mul(&tmp2,&Tmp_P.x,&Tmp_P.x);
     Fp2_mul_ui(&tmp2,&tmp2,3);
     Fp2_mul(&lambda,&tmp1,&tmp2);
     Fp2_sqr(&tmp1,&lambda);
     Fp2_mul_ui(&tmp2,&Tmp_P.x,2);
     Fp2_sub(&ANS->x,&tmp1,&tmp2);
     Fp2_sub(&tmp1,&Tmp_P.x,&ANS->x);
     Fp2_mul(&tmp2,&lambda,&tmp1);
     Fp2_sub(&ANS->y,&tmp2,&Tmp_P.y);
     Fp2_clear(&tmp1);
     Fp2_clear(&tmp2);
     Fp2_clear(&lambda);
     EFp2_clear(&Tmp_P);
 }
EFp2_init()
void EFp2_init (EFp2 * P)
Initialize an EFp type structure
Parameters
[in] P - input P in EFp2.
Definition at line 32 of file bn_efp2.c.
References Fp2_init().
Referenced by bls12_2split_G2_scm(), bls12_4split_G2_scm(), bls12_f_ltq(), bls12_ff_ltt(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_plain_G2_scm(), bls12_Pseudo_8_sparse_mapping(), and EFp2_SCM().
{
     Fp2_init(&P->x);
     Fp2_init(&P->y);
     P->infinity=0;
 }
EFp2_printf()
void EFp2_printf (EFp2 * P, char * str)
Prints an EFp2 type structure
Parameters
[in] P - input P in EFp2.
[in] str - any string to print.
Definition at line 43 of file bn_efp2.c.
References Fp2_printf().
{
     gmp_printf("%s",str);
     if(P->infinity==0){
         gmp_printf("(");
         Fp2_printf(&P->x,"");
         gmp_printf(",");
         Fp2_printf(&P->y,"");
         gmp_printf(")");
     }else{
         gmp_printf("infinity");
     }
 }
EFp2_rational_point()
void EFp2_rational_point (EFp2 * P)
Generate an EFp2 rational point
Parameters
[in] P - input rational point P and.
Definition at line 80 of file bn_efp2.c.
References Fp2_init(), and Fp2_set_random().
{
     Fp2 tmp1,tmp2;
     Fp2_init(&tmp1);
     Fp2_init(&tmp2);
     gmp_randstate_t state;
     gmp_randinit_default (state);
     gmp_randseed_ui(state,(unsigned long)time(NULL));
     while(1){
         Fp2_set_random(&P->x,state);
         Fp2_sqr(&tmp1,&P->x);
         Fp2_mul(&tmp2,&tmp1,&P->x);
         mpz_sub(tmp2.x0.x0,tmp2.x0.x0,curve_parameters.curve_b);
         if(Fp2_legendre(&tmp2)==1){
             Fp2_sqrt(&P->y,&tmp2);
             break;
         }
     }
     Fp2_clear(&tmp1);
     Fp2_clear(&tmp2);
 }
EFp2_SCM()
void EFp2_SCM (EFp2 * ANS, EFp2 * P, mpz_t scalar)
ECA in EFp2 rational point
Parameters
[in] ANS - output.
[in] P1 - input P1 in EFp2.
[in] scalar - input scalar in mpz_t integer.
Definition at line 184 of file bn_efp2.c.
References EFp2_clear(), EFp2_ECA(), EFp2_ECD(), EFp2_init(), and EFp2_set().
Referenced by bls12_plain_G2_scm().
{
     if(mpz_cmp_ui(scalar,0)==0){
         ANS->infinity=1;
         return;
     }else if(mpz_cmp_ui(scalar,1)==0){
         EFp2_set(ANS,P);
         return;
     }
     EFp2 Tmp_P,Next_P;
     EFp2_init(&Tmp_P);
     EFp2_set(&Tmp_P,P);
     EFp2_init(&Next_P);
     int i,length;
     length=(int)mpz_sizeinbase(scalar,2);
     char binary[length];
     mpz_get_str(binary,2,scalar);
     EFp2_set(&Next_P,&Tmp_P);
     for(i=1; i<length; i++){
         EFp2_ECD(&Next_P,&Next_P);
         if(binary[i]=='1'){
             EFp2_ECA(&Next_P,&Next_P,&Tmp_P);
         }
     }
     EFp2_set(ANS,&Next_P);
     EFp2_clear(&Next_P);
     EFp2_clear(&Tmp_P);
 }
EFp2_set()
void EFp2_set (EFp2 * ANS, EFp2 * P)
Sets EFp2 point an EFp2 type structure
Parameters
[in] ANS - output.
[in] P - input P in EFp2.
Definition at line 56 of file bn_efp2.c.
References Fp2_set().
Referenced by bls12_2split_G2_scm(), bls12_4split_G2_scm(), bls12_f_ltq(), bls12_ff_ltt(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_Pseudo_8_sparse_mapping(), EFp2_ECA(), and EFp2_SCM().
{
     Fp2_set(&ANS->x,&P->x);
     Fp2_set(&ANS->y,&P->y);
     ANS->infinity=P->infinity;
 }
EFp2_set_mpz()
void EFp2_set_mpz (EFp2 * ANS, mpz_t A)
Sets mpz_t in an EFp2 type structure
Parameters
[in] ANS - output.
[in] str - input A in mpz_t int.
Definition at line 68 of file bn_efp2.c.
References Fp2_set_mpz().
{
     Fp2_set_mpz(&ANS->x,A);
     Fp2_set_mpz(&ANS->y,A);
     ANS->infinity=0;
 }
EFp2_set_neg()
void EFp2_set_neg (EFp2 * ANS, EFp2 * P)
Negate an EFp2 type structure
Parameters
[in] ANS - output.
[in] P - input P in EFp2.
Definition at line 74 of file bn_efp2.c.
References Fp2_set(), and Fp2_set_neg().
Referenced by bls12_4split_G2_scm(), bls12_Miller_algo_for_opt_ate(), and bls12_Miller_algo_for_plain_ate().
{
     Fp2_set(&ANS->x,&P->x);
     Fp2_set_neg(&ANS->y,&P->y);
     ANS->infinity=P->infinity;
 }
EFp2_set_ui()
void EFp2_set_ui (EFp2 * ANS, unsigned long int u)
Sets unsigned int an EFp2 type structure
Parameters
[in] ANS - output.
[in] u - input u in us integer.
Definition at line 62 of file bn_efp2.c.
References Fp2_set_ui().
{
     Fp2_set_ui(&ANS->x,UI);
     Fp2_set_ui(&ANS->y,UI);
     ANS->infinity=0;
 }