ELiPS for BN and BLS12 curve: /Users/khandaker/Development/elips_bn_bls/include/ELiPS_bn_bls/bn_efp.h File Reference
bn_efp.h File Reference
Paring over BARRETO-NAEHRIG (BN) Curve related files
#include <ELiPS_bn_bls/curve_dtypes.h>
Functions
void EFp_init (EFp *P)
void EFp_clear (EFp *P)
void EFp_printf (EFp *P, char *str)
void EFp_set (EFp *ANS, EFp *P)
void EFp_set_ui (EFp *ANS, unsigned long int UI)
void EFp_set_mpz (EFp *ANS, mpz_t A)
void EFp_set_neg (EFp *ANS, EFp *P)
void EFp_rational_point_bn (EFp *P)
void EFp_rational_point_bls12 (EFp *P)
void EFp_ECD (EFp *ANS, EFp *P)
void EFp_ECA (EFp *ANS, EFp *P1, EFp *P2)
void EFp_SCM (EFp *ANS, EFp *P, mpz_t scalar)
Detailed Description
Interaface for ellipti cuve operation in BN and BLS12 curve
Definition in file bn_efp.h.
Function Documentation
EFp_clear()
void EFp_clear (EFp * P)
clear of memory an EFp type structure
Parameters
[in] P - input P in EFp.
Definition at line 37 of file bn_efp.c.
References Fp_clear(), and EFp::y.
Referenced by bls12_f_ltp_vtp_for_tate(), bls12_ff_ltt_vtt_for_tate(), bls12_generate_G1_point(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_Miller_algo_for_tate(), bls12_plain_G1_scm(), EFp_ECA(), EFp_ECD(), and EFp_SCM().
                       {
     Fp_clear(&P->x);
     Fp_clear(&P->y);
 }
EFp_ECA()
void EFp_ECA (EFp * ANS, EFp * P1, EFp * P2)
Elliptiptic curve addition in EFp ANS = P1+P2 for BN and BLS curve
Parameters
[out] ANS - output
[in] P1 - passed input pointer in EFp
[in] P1 - passed input pointer in EFp
Definition at line 162 of file bn_efp.c.
References EFp_clear(), EFp_ECD(), EFp_init(), EFp_set(), Fp_clear(), Fp_cmp(), Fp_init(), Fp_inv(), Fp_mul(), Fp_sub(), EFp::infinity, and EFp::y.
Referenced by bls12_2split_G1_scm(), and EFp_SCM().
{
     if(P1->infinity==1){
         EFp_set(ANS,P2);
         return;
     }else if(P2->infinity==1){
         EFp_set(ANS,P1);
         return;
     }else if(Fp_cmp(&P1->x,&P2->x)==0){
         if(Fp_cmp(&P1->y,&P2->y)!=0){
             ANS->infinity=1;
             return;
         }else{
             EFp_ECD(ANS,P1);
             return;
         }
     }
     EFp Tmp_P1,Tmp_P2;
     EFp_init(&Tmp_P1);
     EFp_set(&Tmp_P1,P1);
     EFp_init(&Tmp_P2);
     EFp_set(&Tmp_P2,P2);
     Fp tmp1,tmp2,lambda;
     Fp_init(&tmp1);
     Fp_init(&tmp2);
     Fp_init(&lambda);
     Fp_sub(&tmp1,&Tmp_P2.x,&Tmp_P1.x);
     Fp_inv(&tmp1,&tmp1);
     Fp_sub(&tmp2,&Tmp_P2.y,&Tmp_P1.y);
     Fp_mul(&lambda,&tmp1,&tmp2);
     Fp_mul(&tmp1,&lambda,&lambda);
     Fp_sub(&tmp2,&tmp1,&Tmp_P1.x);
     Fp_sub(&ANS->x,&tmp2,&Tmp_P2.x);
     Fp_sub(&tmp1,&Tmp_P1.x,&ANS->x);
     Fp_mul(&tmp2,&lambda,&tmp1);
     Fp_sub(&ANS->y,&tmp2,&Tmp_P1.y);
     //clear
     Fp_clear(&tmp1);
     Fp_clear(&tmp2);
     Fp_clear(&lambda);
     EFp_clear(&Tmp_P1);
     EFp_clear(&Tmp_P2);
 }
EFp_ECD()
void EFp_ECD (EFp * ANS, EFp * P)
Elliptiptic curve doubling ANS = 2[P] in EFp for BN and BLS curve
Parameters
[out] ANS - output
[in] P - passed input pointer in EFp
Definition at line 129 of file bn_efp.c.
References EFp_clear(), EFp_init(), EFp_set(), Fp_clear(), Fp_cmp_zero(), Fp_init(), Fp_inv(), Fp_mul(), Fp_mul_ui(), Fp_sub(), EFp::infinity, and EFp::y.
Referenced by EFp_ECA(), and EFp_SCM().
{
     if(Fp_cmp_zero(&P->y)==0){
         ANS->infinity=1;
         return;
     }
     EFp Tmp_P;
     EFp_init(&Tmp_P);
     EFp_set(&Tmp_P,P);
     Fp tmp1,tmp2,lambda;
     Fp_init(&tmp1);
     Fp_init(&tmp2);
     Fp_init(&lambda);
     Fp_mul_ui(&tmp1,&Tmp_P.y,2);
     Fp_inv(&tmp1,&tmp1);
     Fp_mul(&tmp2,&Tmp_P.x,&Tmp_P.x);
     Fp_mul_ui(&tmp2,&tmp2,3);
     Fp_mul(&lambda,&tmp1,&tmp2);
     Fp_mul(&tmp1,&lambda,&lambda);
     Fp_mul_ui(&tmp2,&Tmp_P.x,2);
     Fp_sub(&ANS->x,&tmp1,&tmp2);
     Fp_sub(&tmp1,&Tmp_P.x,&ANS->x);
     Fp_mul(&tmp2,&lambda,&tmp1);
     Fp_sub(&ANS->y,&tmp2,&Tmp_P.y);
     //clear
     Fp_clear(&tmp1);
     Fp_clear(&tmp2);
     Fp_clear(&lambda);
     EFp_clear(&Tmp_P);
 }
EFp_init()
void EFp_init (EFp * P)
Initialize an EFp type structure
Parameters
[in] P - input P in EFp.
Definition at line 31 of file bn_efp.c.
References Fp_init(), EFp::infinity, and EFp::y.
Referenced by bls12_2split_G1_scm(), bls12_f_ltp_vtp_for_tate(), bls12_ff_ltt_vtt_for_tate(), bls12_generate_G1_point(), bls12_Miller_algo_for_opt_ate(), bls12_Miller_algo_for_plain_ate(), bls12_Miller_algo_for_tate(), bls12_plain_G1_scm(), bls12_Pseudo_8_sparse_mapping(), EFp_ECA(), EFp_ECD(), and EFp_SCM().
                      {
     Fp_init(&P->x);
     Fp_init(&P->y);
     P->infinity=0;
 }
EFp_printf()
void EFp_printf (EFp * P, char * str)
Prints an EFp type structure
Parameters
[in] P - input P in EFp.
[in] str - any string to print.
Definition at line 42 of file bn_efp.c.
References Fp_printf(), EFp::infinity, and EFp::y.
{
     gmp_printf("%s",str);
     if(P->infinity==0){
         gmp_printf("(");
         Fp_printf(&P->x,"");
         gmp_printf(",");
         Fp_printf(&P->y,"");
         gmp_printf(")");
     }else{
         gmp_printf("infinity");
     }
 }
EFp_rational_point_bls12()
void EFp_rational_point_bls12 (EFp * P)
Generate rational point in EFp for BLS12 curve
Parameters
[in] P - passed input pointer in EFp and obtain genterated point
Definition at line 104 of file bn_efp.c.
References curve_params::curve_b, curve_parameters, Fp_add_mpz(), Fp_clear(), Fp_init(), Fp_legendre(), Fp_mul(), Fp_set_random(), Fp_sqrt(), and EFp::y.
Referenced by bls12_generate_G1_point().
{
     Fp tmp1,tmp2,tmp_x;
     Fp_init(&tmp1);
     Fp_init(&tmp2);
     Fp_init(&tmp_x);
     gmp_randstate_t state;
     gmp_randinit_default (state);
     gmp_randseed_ui(state,(unsigned long)time(NULL));
     while(1){
         Fp_set_random(&P->x,state);
         Fp_mul(&tmp1,&P->x,&P->x);
         Fp_mul(&tmp2,&tmp1,&P->x);
         Fp_add_mpz(&tmp_x,&tmp2,curve_parameters.curve_b);
         if(Fp_legendre(&tmp_x)==1){
             Fp_sqrt(&P->y,&tmp_x);
             break;
         }
     }
     Fp_clear(&tmp1);
     Fp_clear(&tmp2);
     Fp_clear(&tmp_x);
 }
EFp_rational_point_bn()
void EFp_rational_point_bn (EFp * P)
Generate rational point in EFp for BN curve
Parameters
[in] P - passed input pointer in EFp and obtain genterated point
Definition at line 79 of file bn_efp.c.
References curve_params::curve_b, curve_parameters, Fp_clear(), Fp_init(), Fp_legendre(), Fp_mul(), Fp_set_random(), Fp_sqrt(), Fp_sub_mpz(), and EFp::y.
{
     Fp tmp1,tmp2,tmp_x;
     Fp_init(&tmp1);
     Fp_init(&tmp2);
     Fp_init(&tmp_x);
     gmp_randstate_t state;
     gmp_randinit_default (state);
     gmp_randseed_ui(state,(unsigned long)time(NULL));
     while(1){
         Fp_set_random(&P->x,state);
         Fp_mul(&tmp1,&P->x,&P->x);
         Fp_mul(&tmp2,&tmp1,&P->x);
         Fp_sub_mpz(&tmp_x,&tmp2,curve_parameters.curve_b);
         if(Fp_legendre(&tmp_x)==1){
             Fp_sqrt(&P->y,&tmp_x);
             break;
         }
     }
     Fp_clear(&tmp1);
     Fp_clear(&tmp2);
     Fp_clear(&tmp_x);
 }
EFp_SCM()
void EFp_SCM (EFp * ANS, EFp * P, mpz_t scalar)
Elliptiptic Scalar Multiplication (SCM) in EFp ANS = [scalar]P for BN and BLS curve
Parameters
[out] ANS - output
[in] P - passed input pointer in EFp
[in] P1 - input integer
Definition at line 208 of file bn_efp.c.
References EFp_clear(), EFp_ECA(), EFp_ECD(), EFp_init(), EFp_set(), and EFp::infinity.
Referenced by bls12_plain_G1_scm().
{
     if(mpz_cmp_ui(scalar,0)==0){
         ANS->infinity=1;
         return;
     }else if(mpz_cmp_ui(scalar,1)==0){
         EFp_set(ANS,P);
         return;
     }
     EFp Tmp_P,Next_P;
     EFp_init(&Tmp_P);
     EFp_set(&Tmp_P,P);
     EFp_init(&Next_P);
     int i,length;
     length=(int)mpz_sizeinbase(scalar,2);
     char binary[length];
     mpz_get_str(binary,2,scalar);
     EFp_set(&Next_P,&Tmp_P);
     for(i=1; i<length; i++){
         EFp_ECD(&Next_P,&Next_P);
         if(binary[i]=='1'){
             EFp_ECA(&Next_P,&Next_P,&Tmp_P);
         }
     }
     EFp_set(ANS,&Next_P);
     EFp_clear(&Next_P);
     EFp_clear(&Tmp_P);
 }
EFp_set()
void EFp_set (EFp * ANS, EFp * P)
Sets an EFp type structure
Parameters
[out] ANS - output ANS is set as P in EFp.
[in] P - input P in EFp.
Definition at line 55 of file bn_efp.c.
References Fp_set(), EFp::infinity, and EFp::y.
Referenced by bls12_2split_G1_scm(), bls12_f_ltp_vtp_for_tate(), bls12_ff_ltt_vtt_for_tate(), bls12_Miller_algo_for_tate(), bls12_Pseudo_8_sparse_mapping(), EFp_ECA(), EFp_ECD(), and EFp_SCM().
{
     Fp_set(&ANS->x,&P->x);
     Fp_set(&ANS->y,&P->y);
     ANS->infinity=P->infinity;
 }
EFp_set_mpz()
void EFp_set_mpz (EFp * ANS, mpz_t A)
Sets an EFp type structure
Parameters
[out] ANS - output ANS is set as EFp.
[in] UI - input in GMP mpz_t
Definition at line 67 of file bn_efp.c.
References Fp_set_mpz(), EFp::infinity, and EFp::y.
{
     Fp_set_mpz(&ANS->x,A);
     Fp_set_mpz(&ANS->y,A);
     ANS->infinity=0;
 }
EFp_set_neg()
void EFp_set_neg (EFp * ANS, EFp * P)
Negate EFp
Parameters
[out] ANS - output pointer.
[in] UI - input pointer in EFp
Definition at line 73 of file bn_efp.c.
References Fp_set(), Fp_set_neg(), EFp::infinity, and EFp::y.
{
     Fp_set(&ANS->x,&P->x);
     Fp_set_neg(&ANS->y,&P->y);
     ANS->infinity=P->infinity;
 }
EFp_set_ui()
void EFp_set_ui (EFp * ANS, unsigned long int UI)
Sets an EFp type structure
Parameters
[out] ANS - output ANS is set an unsigned long int.
[in] UI - input in unsigned long int
Definition at line 61 of file bn_efp.c.
References Fp_set_ui(), EFp::infinity, and EFp::y.
{
     Fp_set_ui(&ANS->x,UI);
     Fp_set_ui(&ANS->y,UI);
     ANS->infinity=0;
 }